name: Build and Deploy to site-branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Build Site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build -d site

    - name: Checkout site-branch
      run: |
        git checkout -b site-branch
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        
    - name: Commit and Push to site-branch
      run: |
        git add -A
        git commit -m "Auto-build from GitHub Actions"
        git push -f origin site-branch
