name: Build and Deploy to gh-pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # You can specify your desired Node.js version here

    - name: Build Site
      run: |
        gem install bundler
        bundle install
        npm install  # If you have any Node.js dependencies
        JEKYLL_ENV=production bundle exec jekyll build
